# -*- coding: utf-8 -*-
"""Análisis de Correlación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-iUx5g4nPCyaw_LCRhnWRn5tRg-dtpz

Análisis de Datos CSV CORRELACIÓN

Importar librerías
"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""CARGAR ARCHIVO CSV"""

url_correlacion = "https://raw.githubusercontent.com/eduardorivas2517502022/Parcial4-RivasEduardo-2517502022/refs/heads/main/csv/clave_G_correlacion.csv"

df_correlacion = pd.read_csv(url_correlacion)

df_correlacion.head()

"""REVISAR ESTRUCTURA DEL DATASET"""

df_correlacion.info()
df_correlacion.isnull().sum()
df_correlacion.duplicated().sum()

"""Muestra estadisticas generales, nombra columnas, selecciona variables numericas y Convierte datos numéricos correctamente"""

df_correlacion.describe()
df_correlacion.columns
variables_numericas = df_correlacion.select_dtypes(
    include=['int64', 'float64']
)

variables_numericas = variables_numericas.apply(
    pd.to_numeric,
    errors='coerce'
)

"""Reemplazar valores nulos"""

variables_numericas = variables_numericas.fillna(
    variables_numericas.mean()
)

"""Calcula matriz de correlación"""

matriz_correlacion = variables_numericas.corr()

matriz_correlacion

"""Crea mapa de calor"""

plt.figure(figsize=(10,7))

sns.heatmap(
    matriz_correlacion,
    annot=True,
    cmap='coolwarm'
)

plt.title('Mapa de calor de correlaciones')

plt.show()

"""Muestra correlaciones positivas más importantes"""

correlaciones_positivas = matriz_correlacion.unstack()

correlaciones_positivas = correlaciones_positivas.sort_values(
    ascending=False
)

correlaciones_positivas = correlaciones_positivas[
    correlaciones_positivas < 1
]

correlaciones_positivas.head(10)

"""Muestra correlaciones negativas más importantes"""

correlaciones_negativas = matriz_correlacion.unstack()

correlaciones_negativas = correlaciones_negativas.sort_values()

correlaciones_negativas.head(10)