# -*- coding: utf-8 -*-
"""Análisis de Asociación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhorgVhY5MnWRM7v_YBluU9ifvsMO1_8

Análisis de Datos CSV ASOCIACIÓN

iMPORTACIÓN DE LIBRERIAS
"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd

from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

"""CARGAR ARCHIVO CSV"""

url_asociacion = "https://raw.githubusercontent.com/eduardorivas2517502022/Parcial4-RivasEduardo-2517502022/refs/heads/main/csv/clave_G_asociacion.csv"

df_asociacion = pd.read_csv(url_asociacion)

df_asociacion.head()

"""REVISAR ESTRUCTURA DEL DATASET"""

df_asociacion.info()
df_asociacion.isnull().sum()
df_asociacion.duplicated().sum()
df_asociacion.columns

"""CREACIÓN DE TRANSACCIONES Y Convertir a formato transaccional"""

transacciones = df_asociacion.groupby('transaccion_id')['item'].apply(list).tolist()

te = TransactionEncoder()
te_array = te.fit(transacciones).transform(transacciones)

df_transacciones = pd.DataFrame(te_array, columns=te.columns_)

df_transacciones.head()

"""Aplicar algoritmo Apriori"""

frequent_itemsets = apriori(
    df_transacciones,
    min_support=0.05,
    use_colnames=True
)

frequent_itemsets.head()

"""Generar reglas de asociación"""

reglas = association_rules(
    frequent_itemsets,
    metric='confidence',
    min_threshold=0.4
)

"""Ordenar reglas por Lift"""

reglas = reglas.sort_values(by='lift', ascending=False)

reglas[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

"""Mostrar las 10 reglas más importantes"""

top_10 = reglas[
    [
        'antecedents',
        'consequents',
        'support',
        'confidence',
        'lift'
    ]
].head(10)

top_10