# -*- coding: utf-8 -*-
"""Análisis Agrupación o Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJ0G8yBI3gPtI00V84zAI7TyBb3hvf-5

Análisis de Datos CSV Agrupación

Importar librerías
"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

"""CARGAR ARCHIVO CSV"""

url_agrupacion = "https://raw.githubusercontent.com/eduardorivas2517502022/Parcial4-RivasEduardo-2517502022/refs/heads/main/csv/clave_G_agrupacion.csv"

df_agrupacion = pd.read_csv(url_agrupacion)

df_agrupacion.head()

"""REVISAR ESTRUCTURA DEL DATASET y Reemplazar valores nulos"""

df_agrupacion.info()
df_agrupacion.isnull().sum()
df_agrupacion['satisfaccion'] = df_agrupacion['satisfaccion'].fillna(df_agrupacion['satisfaccion'].median())
df_agrupacion.duplicated().sum()

"""Seleccionar variables para clustering"""

variables_cluster = df_agrupacion[
    [
        'edad',
        'ingresos',
        'frecuencia_uso',
        'gasto_promedio',
        'satisfaccion',
        'reclamos',
        'antiguedad_meses'
    ]
].copy()

"""Convertir datos numéricos, Reemplazar valores faltantes y Escalar o normalizar datos"""

variables_cluster = variables_cluster.apply(pd.to_numeric, errors='coerce')
variables_cluster = variables_cluster.fillna(variables_cluster.mean())

scaler = StandardScaler()

variables_escaladas = scaler.fit_transform(variables_cluster)

"""Método del codo"""

inercias = []

for k in range(1, 11):
    modelo = KMeans(n_clusters=k, random_state=42, n_init=10)
    modelo.fit(variables_escaladas)
    inercias.append(modelo.inertia_)

"""Graficar método del codo"""

plt.figure(figsize=(8, 5))
plt.plot(range(1, 11), inercias, marker='o')
plt.xlabel('Número de clusters')
plt.ylabel('Inercia')
plt.title('Método del codo')
plt.show()

"""Aplicar K-Means"""

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

df_agrupacion['cluster'] = kmeans.fit_predict(variables_escaladas)

df_agrupacion.head()

"""Contar clientes por grupo y Promedio de variables por cluster"""

df_agrupacion['cluster'].value_counts()
df_agrupacion.groupby('cluster')[
    [
        'edad',
        'ingresos',
        'frecuencia_uso',
        'gasto_promedio',
        'satisfaccion',
        'reclamos',
        'antiguedad_meses'
    ]
].mean()

"""Visualización de clusters"""

plt.figure(figsize=(8, 6))
plt.scatter(
    df_agrupacion['frecuencia_uso'],
    df_agrupacion['gasto_promedio'],
    c=df_agrupacion['cluster']
)

plt.xlabel('Frecuencia de uso')
plt.ylabel('Gasto promedio')
plt.title('Clusters de clientes')
plt.show()

"""Guardar dataset final"""

df_agrupacion.to_csv('dataset_con_clusters.csv', index=False)

print("Archivo dataset_con_clusters.csv creado correctamente")